language: python
python:
  - "3.4"

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  python -m unittest calc_test
  coverage run -m unittest calc_test

# after success
after_success:
  coveralls